### ISSUE TITLE
2.0.2 stopped working under Windows 7

### ISSUE THREAD

**Issue by sergeevabc** [cwansart/sha256sum.exe#5]
2.0.2 (both msvcv140 and 143) throws an error as follows.

![image](https://github.com/user-attachments/assets/e3791102-3b8c-4170-ba84-ecbfd20dc9d3)

2.0.1 (sha256sum-msvcv140) still works fine.

**Comment by apollo7321** [comment]
Thank you for your big report. I guess it has to do with the change of the Windows API. I'll check it later, I've got no computer with me.

What Windows version are you using?

**Comment by sergeevabc** [comment]
> What Windows version are you using?

Windows 7 SP1 x64.

```console
$ ver
Microsoft Windows [Version 6.1.7601]
```

**Comment by apollo7321** [comment]
I checked if there is any way to compile it with the recent changes to work on Windows 7, but as far as I can tell the missing dll is available starting from Windows 8 on.

I will check if I can use the older WinAPI calls but I won't make any promises.

I wrote this software to work in Windows 10 GitLab workers, it was never indented to be backward compatible, its goal is to be small.

**Comment by apollo7321** [comment]
Okay, it was relatively easy, only 2 functions. I tried different compilation combinations. Could you check if one of those work for you? I checked all of them in a Windows 7 VM and they seem to work: 
[sha256sum-vc140.zip](https://github.com/user-attachments/files/17778791/sha256sum-vc140.zip)

I did further experimentation and it seems that I can use msvc143 and a newer target platform. If vcredist 143 is installed it should work with the changes on Windows 7.
I will do some more testing and then I will release a new release with msvc143 and target platform 10.0.22000.0.

**Comment by sergeevabc** [comment]
> [sha256sum-vc140.zip](https://github.com/user-attachments/files/17778791/sha256sum-vc140.zip)

* `sha256sum-vc140-8.1.exe` works
* `sha256sum-vc140-10.0.18362.0.exe` works
* `sha256sum-vc140-10.0.22000.0.exe` works

**Comment by apollo7321** [comment]
Great, thank you for testing. I created a new release with the changes: https://github.com/cwansart/sha256sum.exe/releases/tag/v2.0.3
